# Generated by Django 3.2.4 on 2024-08-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_w2n3ng', null=True, upload_to='images/'),
        ),
    ]
